// http://www.apache.org/licenses/LICENSE-2.0
// Copyright 2026 Perttu Ahola <celeron55@gmail.com>
// SPDX-License-Identifier: Apache-2.0 OR MIT
//
// The Luanti world importer, included by luanti.cpp inside struct Module
// ([SPLITS]: moved out as it was).

	// The id this run gave a Luanti node name, or the one "unknown" has.
	// Asked of Lua, because the aliases and the content ids are its tables.
	uint32_t import_content_id(const ss_ &name, bool &known)
	{
		auto it = m_import_ids.find(name);
		if(it != m_import_ids.end()){
			known = it->second.second;
			return it->second.first;
		}
		interface::MutexScope ms(m_lua_mutex);
		lua_State *L = m_lua;
		int base = lua_gettop(L);
		lua_getglobal(L, "core");
		lua_getfield(L, -1, "__content_id_or_unknown");
		lua_pushstring(L, name.c_str());
		uint32_t id = 0;
		known = false;
		if(lua_pcall(L, 1, 2, 0) != 0){
			log_w(MODULE, "__content_id_or_unknown(): %s",
					lua_tostring(L, -1) ? lua_tostring(L, -1) : "?");
		} else {
			id = (uint32_t)lua_tonumber(L, -2);
			known = lua_toboolean(L, -1) != 0;
		}
		lua_settop(L, base);
		m_import_ids[name] = {id, known};
		return id;
	}

	// The LBMs a world has already had, which Luanti keeps in env_meta.txt as
	// "name~time;name~time;" and uses to decide what runs on a mapblock: an
	// LBM whose introduction time is older than the block does not run on it,
	// which for a world generated by the game that already had the LBM means
	// never. An imported world brings that list with it and this keeps it, so
	// that the module leaves alone what Luanti would leave alone.
	//
	// **What it cost while ignored.** VoxeLibre's
	// mcl_mapgen_core:fix_grass_palette_indexes re-derives every grass
	// block's palette index from the current version's biome code. The
	// reference world was generated five minor versions ago, so sweeping it
	// repainted its grass a different green -- and that was read as a
	// rendering fault for two days. See [GREEN_BIAS] in
	// doc/plan/rendering_plan.md.
	static ss_ lbm_names_of(const ss_ &field)
	{
		ss_ out;
		size_t at = 0;
		while(at < field.size()){
			const size_t end = field.find(';', at);
			const ss_ one = field.substr(at,
					end == ss_::npos ? ss_::npos : end - at);
			const size_t tilde = one.rfind('~');
			if(tilde != ss_::npos && tilde > 0)
				out += one.substr(0, tilde) + ";";
			if(end == ss_::npos)
				break;
			at = end + 1;
		}
		return out;
	}

	// The clock a Luanti world was left at: env_meta.txt, which is lines of
	// "key = value" and then EnvArgsEnd. Three of them are the clock, one is
	// the LBM bookkeeping above, and the rest is the object bookkeeping,
	// which has no meaning here yet.
	void import_clock(const ss_ &luanti_world_path)
	{
		ss_ path = luanti_world_path+"/env_meta.txt";
		std::ifstream ifs(path.c_str(), std::ios::binary);
		if(!ifs.good()){
			log_v(MODULE, "import_world(): no env_meta.txt; the clock stays "
					"where it was");
			return;
		}
		double time_of_day = -1, game_time = -1, day_count = -1;
		ss_ line;
		while(std::getline(ifs, line)){
			if(!line.empty() && line[line.size() - 1] == '\r')
				line.resize(line.size() - 1);
			if(line == "EnvArgsEnd")
				break;
			size_t eq = line.find(" = ");
			if(eq == ss_::npos)
				continue;
			ss_ key = line.substr(0, eq);
			ss_ value = line.substr(eq + 3);
			if(key == "time_of_day")
				time_of_day = atof(value.c_str());
			else if(key == "game_time")
				game_time = atof(value.c_str());
			else if(key == "day_count")
				day_count = atof(value.c_str());
			else if(key == "lbm_introduction_times"){
				const ss_ names = lbm_names_of(value);
				if(m_store)
					m_store->set("lbm_introduced", names);
				publish_lbm_introduced();
				log_v(MODULE, "import_world(): the world has already had "
						"these LBMs: %s", cs(names));
			}
		}
		if(time_of_day < 0 && game_time < 0 && day_count < 0){
			log_w(MODULE, "import_world(): %s says nothing about the clock",
					cs(path));
			return;
		}
		// Luanti's day is 24000 units long and this module's is one
		double tod = time_of_day < 0 ? 0.5 : time_of_day / 24000.0;
		interface::MutexScope ms(m_lua_mutex);
		lua_State *L = m_lua;
		int base = lua_gettop(L);
		lua_getglobal(L, "core");
		lua_getfield(L, -1, "__set_clock");
		lua_pushnumber(L, tod);
		lua_pushnumber(L, game_time < 0 ? 0 : game_time);
		lua_pushnumber(L, day_count < 0 ? 0 : day_count);
		if(lua_pcall(L, 3, 0, 0) != 0)
			log_w(MODULE, "import_world(): __set_clock(): %s",
					lua_tostring(L, -1) ? lua_tostring(L, -1) : "?");
		lua_settop(L, base);
		log_i(MODULE, "import_world(): the clock it was left at: day %i, "
				"time %.4f, %.0f seconds played", (int)day_count, tod,
				game_time);
	}

	// A Luanti world's mod_storage.sqlite: what its mods remember, per mod,
	// into the files this module keeps a mod's storage in.
	// A Luanti world's players.sqlite: where each player stood, which way
	// they looked, their health and breath, what a mod wrote on them and
	// what they carried. The save has somewhere to put one now -- step 5d of
	// doc/plan/world_persistence_plan.md -- and this is the other half.
	//
	// simplified: the sqlite database only. Luanti still reads a world whose
	// players are one text file each under players/, and writing that reader
	// is worth it when a world that has one turns up.
	struct Player {
		double pitch = 0.0, yaw = 0.0;
		double x = 0.0, y = 0.0, z = 0.0;
		int hp = 20, breath = 10;
		sm_<ss_, ss_> fields;
		// What Luanti's own player file keeps the metadata in: one JSON
		// object, which the Lua side decodes because that is where the
		// parser is
		ss_ extended_attributes;
		// The list's name, and the item string of each slot in it. The
		// slots are kept by index because a database row says which one
		// it is and an empty slot has no row at all.
		sm_<ss_, sm_<int, ss_>> lists;
		sm_<ss_, int> list_sizes;
	};

	// Luanti keeps a player's position in BS units, which is nodes times
	// ten, and their angles in degrees; a node and a radian is what
	// everything on this side of the import is in.
	static constexpr double DEG_TO_RAD = 3.14159265358979323846 / 180.0;

	void import_players(const ss_ &luanti_world_path)
	{
		sm_<ss_, Player> players;
		read_player_database(luanti_world_path, players);
		// A world written before players.sqlite has a file per player
		// instead. Both are read, and the database wins where a name is in
		// both, which is the order Luanti migrates them in.
		read_player_files(luanti_world_path, players);
		if(players.empty())
			return;
		push_players(players);
	}

	void read_player_database(const ss_ &luanti_world_path,
			sm_<ss_, Player> &players)
	{
		ss_ db_path = luanti_world_path+"/players.sqlite";
		if(!interface::fs::path_exists(db_path))
			return;
		sqlite3 *db = nullptr;
		if(sqlite3_open_v2(db_path.c_str(), &db, SQLITE_OPEN_READONLY,
				nullptr) != SQLITE_OK){
			log_w(MODULE, "import_world(): %s: %s", cs(db_path),
					db ? sqlite3_errmsg(db) : "cannot open");
			sqlite3_close(db);
			return;
		}
		auto query = [&](const char *sql,
				const std::function<void(sqlite3_stmt*)> &row){
			sqlite3_stmt *st = nullptr;
			if(sqlite3_prepare_v2(db, sql, -1, &st, nullptr) != SQLITE_OK){
				log_w(MODULE, "import_world(): %s: %s", cs(db_path),
						sqlite3_errmsg(db));
				return;
			}
			while(sqlite3_step(st) == SQLITE_ROW)
				row(st);
			sqlite3_finalize(st);
		};
		auto text = [](sqlite3_stmt *st, int i){
			const char *p = (const char*)sqlite3_column_blob(st, i);
			int n = sqlite3_column_bytes(st, i);
			return ss_(p ? p : "", (size_t)(n > 0 ? n : 0));
		};
		query("SELECT name, pitch, yaw, posX, posY, posZ, hp, breath"
				" FROM player", [&](sqlite3_stmt *st){
			Player &p = players[text(st, 0)];
			// Both in degrees in the file and both in the same sense the
			// Lua API uses: the pitch positive downwards, the yaw
			// counter-clockwise from +Z. They become look.v and look.h as
			// they are.
			p.pitch = sqlite3_column_double(st, 1) * DEG_TO_RAD;
			p.yaw = sqlite3_column_double(st, 2) * DEG_TO_RAD;
			p.x = sqlite3_column_double(st, 3) / 10.0;
			p.y = sqlite3_column_double(st, 4) / 10.0;
			p.z = sqlite3_column_double(st, 5) / 10.0;
			p.hp = sqlite3_column_int(st, 6);
			p.breath = sqlite3_column_int(st, 7);
		});
		if(players.empty()){
			sqlite3_close(db);
			return;
		}
		query("SELECT player, metadata, value FROM player_metadata",
				[&](sqlite3_stmt *st){
			auto it = players.find(text(st, 0));
			if(it != players.end())
				it->second.fields[text(st, 1)] = text(st, 2);
		});
		// inv_id is which list it is and inv_name what it is called; an
		// unnamed one is "main", which is what Luanti's own default is
		sm_<ss_, sm_<int, ss_>> list_names;
		query("SELECT player, inv_id, inv_name, inv_size"
				" FROM player_inventories", [&](sqlite3_stmt *st){
			ss_ who = text(st, 0);
			auto it = players.find(who);
			if(it == players.end())
				return;
			ss_ name = text(st, 2);
			if(name == "")
				name = "main";
			list_names[who][sqlite3_column_int(st, 1)] = name;
			it->second.list_sizes[name] = sqlite3_column_int(st, 3);
		});
		query("SELECT player, inv_id, slot_id, item"
				" FROM player_inventory_items", [&](sqlite3_stmt *st){
			ss_ who = text(st, 0);
			auto it = players.find(who);
			if(it == players.end())
				return;
			auto names = list_names.find(who);
			if(names == list_names.end())
				return;
			auto name = names->second.find(sqlite3_column_int(st, 1));
			if(name == names->second.end())
				return;
			// Luanti counts a slot from zero and everything Lua-side counts
			// from one
			it->second.lists[name->second][sqlite3_column_int(st, 2) + 1] =
					text(st, 3);
		});
		sqlite3_close(db);
	}

	// A world written before players.sqlite: one file per player under
	// players/, holding what the database row holds -- "key = value" lines,
	// a PlayerArgsEnd, and then the inventory in the same shape a node's
	// metadata carries one, which is why mapblock.h's reader is what reads
	// it.
	//
	// A name Luanti could not use as a file name is written with the
	// unusable bytes as _<hex>; the name inside the file is the real one, so
	// that is what is taken and the file name is only how it was found.
	void read_player_files(const ss_ &luanti_world_path,
			sm_<ss_, Player> &players)
	{
		const ss_ dir = luanti_world_path+"/players";
		if(!interface::fs::path_exists(dir))
			return;
		size_t read = 0;
		for(const interface::fs::Node &n : interface::fs::list_directory(dir)){
			if(n.is_directory || n.name == "." || n.name == "..")
				continue;
			std::ifstream ifs(dir+"/"+n.name, std::ios::binary);
			if(!ifs.good())
				continue;
			std::ostringstream os;
			os<<ifs.rdbuf();
			const ss_ data = os.str();
			luanti_mapblock::Reader r(data);
			Player p;
			ss_ name;
			bool ended = false;
			while(r.p < data.size()){
				const ss_ line = r.line();
				if(line == "PlayerArgsEnd"){
					ended = true;
					break;
				}
				const size_t eq = line.find('=');
				if(eq == ss_::npos)
					continue;
				ss_ key = trimmed(line.substr(0, eq));
				ss_ value = trimmed(line.substr(eq + 1));
				if(key == "name")
					name = value;
				else if(key == "pitch")
					p.pitch = atof(value.c_str()) * DEG_TO_RAD;
				else if(key == "yaw")
					p.yaw = atof(value.c_str()) * DEG_TO_RAD;
				else if(key == "hp")
					p.hp = atoi(value.c_str());
				else if(key == "breath")
					p.breath = atoi(value.c_str());
				else if(key == "extended_attributes")
					p.extended_attributes = value;
				else if(key == "position"){
					// "(x,y,z)" in BS units, which is nodes times ten
					double v[3] = {0.0, 0.0, 0.0};
					sscanf(value.c_str(), "(%lf,%lf,%lf)", &v[0], &v[1],
							&v[2]);
					p.x = v[0] / 10.0;
					p.y = v[1] / 10.0;
					p.z = v[2] / 10.0;
				}
			}
			if(name.empty() || !ended){
				log_w(MODULE, "import_world(): players/%s is not a player "
						"file", cs(n.name));
				continue;
			}
			// The inventory, in the shape a node's metadata carries one
			luanti_mapblock::NodeMeta meta;
			luanti_mapblock::read_inventory(r, meta);
			for(const auto &list : meta.lists){
				p.list_sizes[list.first] = (int)list.second.size();
				for(size_t i = 0; i < list.second.size(); i++){
					if(!list.second[i].empty())
						p.lists[list.first][(int)i + 1] = list.second[i];
				}
			}
			// The database wins: a world that has been migrated has both,
			// and the file is then the older of the two
			if(players.count(name) == 0){
				log_i(MODULE, "import_world(): players/%s: %s at "
						"(%.1f, %.1f, %.1f), hp %i, %zu lists", cs(n.name),
						cs(name), p.x, p.y, p.z, p.hp, p.list_sizes.size());
				players[name] = p;
				read++;
			}
		}
		if(read > 0)
			log_i(MODULE, "import_world(): %zu players out of files", read);
	}

	static ss_ trimmed(const ss_ &s)
	{
		size_t a = s.find_first_not_of(" \t\r\n");
		if(a == ss_::npos)
			return "";
		size_t b = s.find_last_not_of(" \t\r\n");
		return s.substr(a, b - a + 1);
	}

	void push_players(const sm_<ss_, Player> &players)
	{
		size_t imported = 0;
		for(const auto &pair : players){
			interface::MutexScope ms(m_lua_mutex);
			lua_State *L = m_lua;
			int base = lua_gettop(L);
			const Player &p = pair.second;
			lua_getglobal(L, "core");
			lua_getfield(L, -1, "__import_player");
			lua_pushstring(L, pair.first.c_str());
			lua_newtable(L);
			auto set_number = [&](const char *key, double value){
				lua_pushnumber(L, value);
				lua_setfield(L, -2, key);
			};
			lua_newtable(L);
			set_number("x", p.x);
			set_number("y", p.y);
			set_number("z", p.z);
			lua_setfield(L, -2, "pos");
			lua_newtable(L);
			set_number("h", p.yaw);
			set_number("v", p.pitch);
			lua_setfield(L, -2, "look");
			set_number("hp", p.hp);
			set_number("breath", p.breath);
			lua_createtable(L, 0, (int)p.fields.size());
			for(const auto &f : p.fields){
				lua_pushlstring(L, f.second.c_str(), f.second.size());
				lua_setfield(L, -2, f.first.c_str());
			}
			lua_setfield(L, -2, "fields");
			// A player file keeps the same metadata as one JSON object;
			// core.__import_player() decodes it, the parser being there
			if(!p.extended_attributes.empty()){
				lua_pushlstring(L, p.extended_attributes.c_str(),
						p.extended_attributes.size());
				lua_setfield(L, -2, "extended_attributes");
			}
			lua_createtable(L, 0, (int)p.list_sizes.size());
			for(const auto &list : p.list_sizes){
				int size = list.second;
				lua_createtable(L, size, 0);
				auto items = p.lists.find(list.first);
				for(int i = 1; i <= size; i++){
					ss_ item;
					if(items != p.lists.end()){
						auto slot = items->second.find(i);
						if(slot != items->second.end())
							item = slot->second;
					}
					lua_pushlstring(L, item.c_str(), item.size());
					lua_rawseti(L, -2, i);
				}
				lua_setfield(L, -2, list.first.c_str());
			}
			lua_setfield(L, -2, "inventory");
			if(lua_pcall(L, 2, 1, 0) != 0){
				log_w(MODULE, "__import_player(): %s",
						lua_tostring(L, -1) ? lua_tostring(L, -1) : "?");
			} else if(lua_toboolean(L, -1)){
				imported++;
			}
			lua_settop(L, base);
		}
		log_i(MODULE, "import_world(): %zu of %zu players", imported,
				players.size());
	}

	void import_mod_storage(const ss_ &luanti_world_path)
	{
		ss_ db_path = luanti_world_path+"/mod_storage.sqlite";
		if(!interface::fs::path_exists(db_path))
			return;
		sqlite3 *db = nullptr;
		if(sqlite3_open_v2(db_path.c_str(), &db, SQLITE_OPEN_READONLY,
				nullptr) != SQLITE_OK){
			log_w(MODULE, "import_world(): %s: %s", cs(db_path),
					db ? sqlite3_errmsg(db) : "cannot open");
			sqlite3_close(db);
			return;
		}
		sqlite3_stmt *st = nullptr;
		if(sqlite3_prepare_v2(db,
				"SELECT modname, key, value FROM entries ORDER BY modname",
				-1, &st, nullptr) != SQLITE_OK){
			log_w(MODULE, "import_world(): %s: %s", cs(db_path),
					sqlite3_errmsg(db));
			sqlite3_close(db);
			return;
		}
		// Per mod, because that is the unit the storage is a file of
		sm_<ss_, sm_<ss_, ss_>> by_mod;
		while(sqlite3_step(st) == SQLITE_ROW){
			auto column = [&](int i){
				const char *p = (const char*)sqlite3_column_blob(st, i);
				int n = sqlite3_column_bytes(st, i);
				return ss_(p ? p : "", (size_t)(n > 0 ? n : 0));
			};
			by_mod[column(0)][column(1)] = column(2);
		}
		sqlite3_finalize(st);
		sqlite3_close(db);
		if(by_mod.empty())
			return;
		size_t written = 0;
		for(const auto &mod : by_mod){
			interface::MutexScope ms(m_lua_mutex);
			lua_State *L = m_lua;
			int base = lua_gettop(L);
			lua_getglobal(L, "core");
			lua_getfield(L, -1, "__import_mod_storage");
			lua_pushstring(L, mod.first.c_str());
			lua_createtable(L, 0, (int)mod.second.size());
			for(const auto &pair : mod.second){
				lua_pushlstring(L, pair.second.c_str(), pair.second.size());
				lua_setfield(L, -2, pair.first.c_str());
			}
			if(lua_pcall(L, 2, 1, 0) != 0){
				log_w(MODULE, "__import_mod_storage(): %s",
						lua_tostring(L, -1) ? lua_tostring(L, -1) : "?");
			} else {
				written += (size_t)lua_tonumber(L, -1);
			}
			lua_settop(L, base);
		}
		log_i(MODULE, "import_world(): %zu values of %zu mods' storage",
				written, by_mod.size());
	}

	// One node's metadata into the Lua table that holds it. The fields are
	// strings and an inventory is item strings, which is the same shape the
	// save keeps and the same function puts either back.
	void import_node_meta(int32_t x, int32_t y, int32_t z,
			const luanti_mapblock::NodeMeta &meta)
	{
		interface::MutexScope ms(m_lua_mutex);
		lua_State *L = m_lua;
		int base = lua_gettop(L);
		lua_getglobal(L, "core");
		lua_getfield(L, -1, "__set_node_meta");
		lua_createtable(L, 0, 3);
		lua_pushinteger(L, x);
		lua_setfield(L, -2, "x");
		lua_pushinteger(L, y);
		lua_setfield(L, -2, "y");
		lua_pushinteger(L, z);
		lua_setfield(L, -2, "z");
		lua_createtable(L, 0, (int)meta.fields.size());
		for(const auto &pair : meta.fields){
			lua_pushlstring(L, pair.second.c_str(), pair.second.size());
			lua_setfield(L, -2, pair.first.c_str());
		}
		lua_createtable(L, 0, (int)meta.lists.size());
		for(const auto &pair : meta.lists){
			lua_createtable(L, (int)pair.second.size(), 0);
			for(size_t i = 0; i < pair.second.size(); i++){
				lua_pushlstring(L, pair.second[i].c_str(),
						pair.second[i].size());
				lua_rawseti(L, -2, (int)i + 1);
			}
			lua_setfield(L, -2, pair.first.c_str());
		}
		if(lua_pcall(L, 3, 0, 0) != 0)
			log_w(MODULE, "__set_node_meta(): %s",
					lua_tostring(L, -1) ? lua_tostring(L, -1) : "?");
		lua_settop(L, base);
	}

	// The timer on a node that had one, started again where it left off.
	// Luanti keeps a timer with the block; here they are the module's own
	// table and a mod reads them through core.get_node_timer().
	void import_node_timer(int32_t x, int32_t y, int32_t z,
			const luanti_mapblock::NodeTimer &timer)
	{
		char buf[256];
		snprintf(buf, sizeof buf,
				"core.get_node_timer({x=%i, y=%i, z=%i}):set(%f, %f)",
				(int)x, (int)y, (int)z, (double)timer.timeout,
				(double)timer.elapsed);
		try {
			run_chunk_string(buf, "import_node_timer");
		} catch(Exception &e){
			log_w(MODULE, "import_node_timer(): %s", e.what());
		}
	}

	// One of the entities a block was holding. Luanti's static data is a
	// version, the entity's name and the state its on_activate is given;
	// the rest of it -- the hit points, the velocity, which way it faces --
	// is what the entity itself writes into its state when it is worth
	// keeping, so the name and the state are what crosses.
	//
	// Returns whether it was made: a game that does not register the entity
	// the world was holding is the usual reason it is not.
	bool import_static_object(const luanti_mapblock::StaticObject &o,
			ss_ &name_out)
	{
		// 7 is Luanti's LuaEntity. The lower numbers are the engine's own
		// objects from before mods could make one and no world written this
		// decade has any.
		if(o.type != 7)
			return false;
		luanti_mapblock::Reader r(o.data);
		ss_ name, state;
		try {
			r.u8(); // version
			name = r.string16();
			state = r.string32();
		} catch(std::exception &e){
			return false;
		}
		if(name.empty())
			return false;
		name_out = name;
		interface::MutexScope ms(m_lua_mutex);
		lua_State *L = m_lua;
		int base = lua_gettop(L);
		lua_getglobal(L, "core");
		lua_getfield(L, -1, "__import_entity");
		lua_pushnumber(L, o.x);
		lua_pushnumber(L, o.y);
		lua_pushnumber(L, o.z);
		lua_pushlstring(L, name.c_str(), name.size());
		lua_pushlstring(L, state.c_str(), state.size());
		bool made = false;
		if(lua_pcall(L, 5, 1, 0) != 0){
			log_w(MODULE, "__import_entity(): %s",
					lua_tostring(L, -1) ? lua_tostring(L, -1) : "?");
		} else {
			made = lua_toboolean(L, -1) != 0;
		}
		lua_settop(L, base);
		return made;
	}

	// Read a Luanti world into this one: the clock, and as much of the map
	// as this world has room for.
	//
	// One direction and read-only: the Luanti world is never written to. A
	// block that cannot be read is counted and skipped, because a world is
	// worth having with a hole in it, and a name this game does not register
	// becomes "unknown", which is a node you can see and dig rather than a
	// hole.
	//
	// What comes over is the nodes, what hangs off them, the timer on a node
	// that had one and the entities the blocks were holding.
	//
	// simplified: an imported entity is made where it was and is live from
	// then on. Luanti keeps a block's entities with the block and wakes them
	// when somebody comes near; here they are all in the world at once,
	// which is the same shortcut as an object outside the active range
	// staying in the world and has the same upgrade path.

	void import_world(const ss_ &luanti_world_path)
	{
		if(m_game_running)
			throw Exception("luanti: import_world() after run_game(); the "
					"map is read while the world is made, before a "
					"generator has been asked for any part of it");
		m_import_path = luanti_world_path;
	}

	// The import itself, from inside run_game(): the game's nodes are
	// registered, the world exists, and nothing has asked for a section
	// yet. Both of those bound it -- a name is only a node once the mods
	// have loaded, and a section a generator has already been over is a
	// section this would be writing into behind the generator's back.
	void read_luanti_world(const ss_ &luanti_world_path)
	{
		import_clock(luanti_world_path);
		import_mod_storage(luanti_world_path);
		import_players(luanti_world_path);
		ss_ db_path = luanti_world_path+"/map.sqlite";
		if(!interface::fs::path_exists(db_path))
			throw Exception("luanti: no map.sqlite in "+luanti_world_path);
		sqlite3 *db = nullptr;
		int rc = sqlite3_open_v2(db_path.c_str(), &db, SQLITE_OPEN_READONLY,
				nullptr);
		if(rc != SQLITE_OK){
			ss_ err = db ? sqlite3_errmsg(db) : "cannot open";
			sqlite3_close(db);
			throw Exception("luanti: "+db_path+": "+err);
		}
		// Two schemas exist: the older one keys a block by one integer, the
		// newer by three columns. Luanti reads both and so does this.
		sqlite3_stmt *st = nullptr;
		bool by_xyz = false;
		rc = sqlite3_prepare_v2(db, "SELECT pos, data FROM blocks", -1, &st,
				nullptr);
		if(rc != SQLITE_OK){
			by_xyz = true;
			rc = sqlite3_prepare_v2(db, "SELECT x, y, z, data FROM blocks",
					-1, &st, nullptr);
		}
		if(rc != SQLITE_OK){
			ss_ err = sqlite3_errmsg(db);
			sqlite3_close(db);
			throw Exception("luanti: "+db_path+": "+err);
		}
		// What this world has room for. A block that reaches outside is
		// clipped rather than dropped, so that the edge is where the world
		// ends and not where a block boundary is.
		const pv::Vector3DInt32 &s0 = m_section_region.getLowerCorner();
		const pv::Vector3DInt32 &s1 = m_section_region.getUpperCorner();
		const int32_t sx = m_section_size.getX(), sy = m_section_size.getY(),
				sz = m_section_size.getZ();
		const int32_t wx0 = s0.getX() * sx, wy0 = s0.getY() * sy,
				wz0 = s0.getZ() * sz;
		const int32_t wx1 = (s1.getX() + 1) * sx - 1,
				wy1 = (s1.getY() + 1) * sy - 1,
				wz1 = (s1.getZ() + 1) * sz - 1;
		size_t blocks_read = 0, blocks_outside = 0, blocks_failed = 0;
		size_t nodes_written = 0, meta_written = 0, timers_written = 0;
		// The sections this world has been written into, which are the ones
		// no generator is to be run over; see below
		set_<uint64_t> marked;
		size_t objects_written = 0, objects_dropped = 0;
		set_<ss_> unknown_names;
		set_<ss_> unknown_entities;
		// What is made once the map is not being held; see the loop
		sv_<std::pair<pv::Vector3DInt32, luanti_mapblock::NodeTimer>>
				pending_timers;
		sv_<luanti_mapblock::StaticObject> pending_objects;
		sm_<ss_, size_t> counts;
		ss_ first_error;
		const interface::VoxelFormat f = interface::VoxelFormat::luanti();
		const int32_t BS = (int32_t)luanti_mapblock::BLOCK_SIDE;
		voxelworld::access(m_server, m_scene, [&](voxelworld::Instance *world){
			while(sqlite3_step(st) == SQLITE_ROW){
				pv::Vector3DInt16 bp;
				if(by_xyz){
					bp = pv::Vector3DInt16(
							(int16_t)sqlite3_column_int(st, 0),
							(int16_t)sqlite3_column_int(st, 1),
							(int16_t)sqlite3_column_int(st, 2));
				} else {
					bp = luanti_mapblock::block_pos_of_key(
							sqlite3_column_int64(st, 0));
				}
				const int data_column = by_xyz ? 3 : 1;
				int32_t bx = (int32_t)bp.getX() * BS;
				int32_t by = (int32_t)bp.getY() * BS;
				int32_t bz = (int32_t)bp.getZ() * BS;
				int32_t x0 = std::max(bx, wx0), x1 = std::min(bx + BS - 1, wx1);
				int32_t y0 = std::max(by, wy0), y1 = std::min(by + BS - 1, wy1);
				int32_t z0 = std::max(bz, wz0), z1 = std::min(bz + BS - 1, wz1);
				if(x1 < x0 || y1 < y0 || z1 < z0){
					blocks_outside++;
					continue;
				}
				const void *blob = sqlite3_column_blob(st, data_column);
				int blob_size = sqlite3_column_bytes(st, data_column);
				luanti_mapblock::Block block;
				try {
					ss_ data((const char*)blob, (size_t)blob_size);
					luanti_mapblock::deserialize_block(data, block);
				} catch(std::exception &e){
					blocks_failed++;
					if(first_error.empty())
						first_error = e.what();
					continue;
				}
				// The ids are the block's own; every block carries the
				// mapping it was written with
				sm_<uint16_t, uint32_t> ids;
				sm_<uint16_t, bool> is_ignore;
				for(const auto &pair : block.names){
					bool known = false;
					ids[pair.first] = import_content_id(pair.second, known);
					is_ignore[pair.first] = (pair.second == "ignore");
					if(!known)
						unknown_names.insert(pair.second);
				}
				sm_<uint16_t, const ss_*> names_by_id;
				for(const auto &pair : block.names)
					names_by_id[pair.first] = &pair.second;
				// The block as a volume and one write, rather than a
				// section and buffer lookup per voxel. A voxel this leaves
				// undefined -- an "ignore", which is Luanti for "nothing
				// has generated this" -- is a hole set_volume() skips.
				interface::VoxelVolume vol(pv::Region(
						pv::Vector3DInt32(x0, y0, z0),
						pv::Vector3DInt32(x1, y1, z1)));
				for(int32_t z = z0; z <= z1; z++)
				for(int32_t y = y0; y <= y1; y++)
				for(int32_t x = x0; x <= x1; x++){
					size_t i = (size_t)(x - bx) +
							(size_t)(y - by) * BS +
							(size_t)(z - bz) * BS * BS;
					uint16_t raw_id = block.param0[i];
					auto it = ids.find(raw_id);
					if(it == ids.end() || is_ignore[raw_id])
						continue; // Not generated there, so nothing to write
					uint32_t word = 0;
					f.id.set(word, it->second);
					f.light_sky.set(word, block.param1[i] & 0x0f);
					f.light_lamp.set(word, (block.param1[i] >> 4) & 0x0f);
					f.param.set(word, block.param2[i]);
					vol.setVoxelAt(x, y, z, interface::VoxelInstance(word));
					nodes_written++;
					counts[*names_by_id[raw_id]]++;
				}
				// A section this world reaches into is a section that has
				// been generated, by the engine that generated it. Without
				// that mark this one's own generator runs over it later --
				// a section is its generator's to write, so the volume
				// that arrives puts a fresh world where the read one was.
				// A section the import only partly covers keeps the rest
				// of itself undefined, which is what a Luanti world says
				// about a block it does not hold.
				//
				// simplified: the mark is per section and the map is per
				// block, so 64 blocks of a section share one answer. Where
				// the imported world ends mid-section, the rest of that
				// section is not generated either. Per-block would mean
				// generating the section and writing the blocks over it
				// afterwards, which is the source kept open until every
				// section it touches has been generated.
				const pv::Vector3DInt16 sp = section_of(
						pv::Vector3DInt32(x0, y0, z0));
				if(marked.insert(section_key(sp)).second)
					world->set_section_generated(sp);
				world->set_volume(vol, true);
				// What hangs off the nodes: a chest's contents, a sign's
				// text. Only for the part of the block that was written.
				for(const auto &pair : block.meta){
					int32_t mx = bx + (pair.first & 15);
					int32_t my = by + ((pair.first >> 4) & 15);
					int32_t mz = bz + ((pair.first >> 8) & 15);
					if(mx < x0 || mx > x1 || my < y0 || my > y1 ||
							mz < z0 || mz > z1)
						continue;
					import_node_meta(mx, my, mz, pair.second);
					meta_written++;
				}
				// The timers and the entities are kept for afterwards
				// rather than made here: an entity's own on_activate is a
				// mod's code and reads the map, and the map is what this
				// loop is holding. A mod that asks voxelworld for a node
				// from inside a voxelworld access waits for the access it
				// is already inside, which is a server that stops.
				for(const auto &pair : block.timers){
					int32_t tx = bx + (pair.first & 15);
					int32_t ty = by + ((pair.first >> 4) & 15);
					int32_t tz = bz + ((pair.first >> 8) & 15);
					if(tx < x0 || tx > x1 || ty < y0 || ty > y1 ||
							tz < z0 || tz > z1)
						continue;
					pending_timers.push_back(std::make_pair(
							pv::Vector3DInt32(tx, ty, tz), pair.second));
				}
				for(const luanti_mapblock::StaticObject &o : block.objects){
					if(o.x < (float)x0 || o.x > (float)x1 + 1.0f ||
							o.y < (float)y0 || o.y > (float)y1 + 1.0f ||
							o.z < (float)z0 || o.z > (float)z1 + 1.0f)
						continue;
					pending_objects.push_back(o);
				}
				blocks_read++;
			}
		});
		sqlite3_finalize(st);
		sqlite3_close(db);
		// The timers and the entities, now that the map is free: a timer
		// starts again where it left off and an entity is placed where it
		// was, and both of those are a mod's own code
		for(const auto &pair : pending_timers){
			import_node_timer(pair.first.getX(), pair.first.getY(),
					pair.first.getZ(), pair.second);
			timers_written++;
		}
		for(const luanti_mapblock::StaticObject &o : pending_objects){
			ss_ name;
			if(import_static_object(o, name)){
				objects_written++;
			} else {
				objects_dropped++;
				if(!name.empty())
					unknown_entities.insert(name);
			}
		}
		// What it read metadata for is mostly sections nothing has loaded,
		// and those are written out rather than waiting for an unload that
		// will not come
		if(meta_written != 0)
			write_all_node_meta();
		log_i(MODULE, "import_world(): %zu blocks of %s read into the world, "
				"%zu nodes and %zu of them with metadata; %zu blocks outside "
				"it, %zu it could not read; %zu sections it will not "
				"generate",
				blocks_read, cs(luanti_world_path), nodes_written,
				meta_written, blocks_outside, blocks_failed, marked.size());
		if(timers_written != 0 || objects_written != 0 || objects_dropped != 0)
			log_i(MODULE, "import_world(): %zu node timers and %zu entities, "
					"and %zu it could not make",
					timers_written, objects_written, objects_dropped);
		if(!unknown_entities.empty()){
			ss_ list;
			size_t n = 0;
			for(const ss_ &name : unknown_entities){
				if(n++ >= 10){
					list += ", and "+itos(unknown_entities.size() - 10)+
							" more";
					break;
				}
				if(!list.empty())
					list += ", ";
				list += name;
			}
			log_w(MODULE, "import_world(): the world was holding entities "
					"this game does not register: %s", cs(list));
		}
		if(!first_error.empty())
			log_w(MODULE, "import_world(): the first block it could not read: "
					"%s", cs(first_error));
		// What arrived, which is the cheapest thing to compare against what
		// Luanti says is in the same world
		sv_<std::pair<size_t, ss_>> by_count;
		for(const auto &pair : counts)
			by_count.push_back({pair.second, pair.first});
		std::sort(by_count.begin(), by_count.end(),
				[](const std::pair<size_t, ss_> &a,
						const std::pair<size_t, ss_> &b){
			return a.first > b.first;
		});
		ss_ top;
		for(size_t i = 0; i < by_count.size() && i < 5; i++)
			top += (i ? ", " : "") + by_count[i].second + " " +
					itos(by_count[i].first);
		if(!top.empty())
			log_i(MODULE, "import_world(): most of it is %s", cs(top));
		if(!unknown_names.empty()){
			ss_ names;
			size_t n = 0;
			for(const ss_ &name : unknown_names){
				if(n++ >= 8){
					names += ", ...";
					break;
				}
				names += (n > 1 ? ", " : "") + name;
			}
			log_w(MODULE, "import_world(): %zu node names this game does not "
					"register are drawn as unknown: %s",
					unknown_names.size(), cs(names));
		}
	}

	// map_meta.txt: what a Luanti world is made out of -- its seed, which
	// mapgen made it and what that mapgen was told. Before run_game(),
	// because the world is made when the game starts: a mapgen told
	// afterwards has already generated the ground the player stands on.
	//
	// What the save already says is kept, so a world that has been played
	// here keeps its own terrain whatever it is imported over.
	void import_world_settings(const ss_ &luanti_world_path,
			storage::Save *save)
	{
		if(m_game_running)
			throw Exception("luanti: import_world_settings() after "
					"run_game(); the world is already made out of them");
		if(!save)
			throw Exception("luanti: import_world_settings() without a save");
		storage::Store *store = save->store("luanti");
		if(!store)
			return;
		std::ifstream ifs(luanti_world_path+"/map_meta.txt");
		if(!ifs.good())
			return;
		// The names on this side, for the four of Luanti's that mean
		// something to this module's mapgen
		static const sm_<ss_, ss_> WANTED = {
			{"seed", "seed"},
			{"mg_name", "mg_name"},
			{"water_level", "water_level"},
			{"mg_flags", "mg_flags"},
		};
		ss_ taken;
		ss_ line;
		while(std::getline(ifs, line)){
			size_t eq = line.find('=');
			if(eq == ss_::npos)
				continue;
			ss_ key = line.substr(0, eq);
			while(!key.empty() && (key.back() == ' ' || key.back() == '\t'))
				key.pop_back();
			auto it = WANTED.find(key);
			if(it == WANTED.end())
				continue;
			ss_ value = line.substr(eq + 1);
			size_t begin = value.find_first_not_of(" \t");
			if(begin == ss_::npos)
				continue;
			value = value.substr(begin);
			while(!value.empty() && (value.back() == ' ' ||
					value.back() == '\t' || value.back() == '\r'))
				value.pop_back();
			ss_ have;
			if(store->get(it->second, have) && !have.empty())
				continue; // The save's own, and it was here first
			store->set(it->second, value);
			if(!taken.empty())
				taken += ", ";
			taken += it->second+"="+value;
		}
		if(!taken.empty())
			log_i(MODULE, "The imported world is made with %s", cs(taken));
	}
