#!/bin/bash
# SPDX-License-Identifier: Apache-2.0 OR MIT
# tier: full
# cost: 3 min (VoxeLibre, the default box; buildat's emerge is most of it)
# [MAPGEN_DENSITY]: one box of VoxeLibre generated by official Luanti and
# by buildat from the same seed, every node kind counted in both
# (density.lua), side by side with buildat's counts scaled to what it read
# -- a few of its blocks read as ignore, see density.lua. Needs `luanti`
# on the PATH (5.18-dev on this desk) and VoxeLibre in
# user/shared/vanilla/games/mineclone2.
#
#   builtin/luanti/test/density.sh [seed] [x1,y1,z1,x2,y2,z2]
#
# The table goes to local/density/<seed>_<box>.txt as well.
set -u
here=$(cd "$(dirname "$0")/../../.." && pwd)
me=$(cd "$(dirname "$0")" && pwd)
seed=${1:-12345}
box=${2:--112,-64,-112,47,63,47}
out="$here/local/density"
games="$here/user/shared/vanilla/games"
mkdir -p "$out"
run="$out/run"
rm -rf "$run/off_w" "$run/bu/apps/vanilla/saves/density"
mkdir -p "$run/off_w/worldmods/densitymod" "$run/bu/shared/vanilla/games"
cp "$me/density.lua" "$run/off_w/worldmods/densitymod/init.lua"
echo "name = densitymod" > "$run/off_w/worldmods/densitymod/mod.conf"
printf 'gameid = mineclone2\nbackend = sqlite3\n' > "$run/off_w/world.mt"
printf 'fixed_map_seed = %s\nmg_name = v7\n' "$seed" > "$run/off.conf"
# The boxed server reads its fixture and the game under its user directory
[ -d "$run/bu/shared/vanilla/games/mineclone2" ] ||
	cp -r "$games/mineclone2" "$run/bu/shared/vanilla/games/"
cp "$me/density.lua" "$run/bu/shared/vanilla/density.lua"

# Until "DENSITY done", or two minutes without a progress line
wait_done() {
	local log=$1 last=-1 stall=0 n
	while ! grep -aq "DENSITY done" "$log"; do
		n=$(grep -ac "DENSITY emerging\|on_generated by mod after" "$log")
		if [ "$n" = "$last" ]; then stall=$((stall + 2)); else stall=0; last=$n; fi
		[ $stall -ge 120 ] && { echo "no progress for 120 s: $log" >&2; return 1; }
		sleep 2
	done
}

DENSITY_BOX=$box LUANTI_GAME_PATH=$games luanti --server \
	--world "$run/off_w" --gameid mineclone2 --config "$run/off.conf" \
	--port 30041 > "$run/off.log" 2>&1 &
pid=$!
wait_done "$run/off.log"; kill $pid 2>/dev/null; wait $pid 2>/dev/null

cd "$here/Build"
DENSITY_BOX=$box BUILDAT_LUANTI_LUA="$run/bu/shared/vanilla/density.lua" \
	BUILDAT_LUANTI_GAME=mineclone2 BUILDAT_LUANTI_SAVE=density \
	BUILDAT_LUANTI_SEED=$seed bin/buildat_server -u launcher=1 \
	-m ../apps/vanilla -D "$run/bu" -P 29997 > "$run/bu.log" 2>&1 &
pid=$!
wait_done "$run/bu.log"; kill $pid 2>/dev/null; wait $pid 2>/dev/null

python3 - "$run/off.log" "$run/bu.log" "$seed" "$box" <<'PY' | tee "$out/${seed}_${box}.txt"
import sys, re
def read(p):
	d = {}
	for l in open(p, errors="ignore"):
		m = re.search(r"DENSITY ([a-z_0-9]+:[a-z_0-9:]+|air|ignore) (\d+)$",
				l.strip())
		if m:
			d[m.group(1)] = int(m.group(2))
	return d
o, b = read(sys.argv[1]), read(sys.argv[2])
to = sum(v for k, v in o.items() if k != "ignore")
tb = sum(v for k, v in b.items() if k != "ignore")
if not to or not tb:
	print("nothing counted: luanti %d, buildat %d" % (to, tb))
	sys.exit(1)
scale = to / tb
print("seed %s, box %s: luanti read %d, buildat %d (ignore %d; scaled "
		"by %.3f)" % (sys.argv[3], sys.argv[4], to, tb, b.get("ignore", 0),
		scale))
print("%-40s %10s %10s %7s" % ("node", "luanti", "buildat*", "ratio"))
for k in sorted(set(o) | set(b), key=lambda k: -max(o.get(k, 0), b.get(k, 0))):
	if k == "ignore":
		continue
	a, c = o.get(k, 0), b.get(k, 0) * scale
	print("%-40s %10d %10d %7s" % (k, a, c, "%.2f" % (c / a) if a else "new"))
PY
