-- SPDX-License-Identifier: Apache-2.0 OR MIT
-- What an imported Luanti world brought with it besides its nodes: the
-- entities its blocks were holding, and the timers on its nodes.
--
--   BUILDAT_LUANTI_GAME=mineclone2 BUILDAT_LUANTI_SAVE=import_check \
--   BUILDAT_LUANTI_IMPORT=/path/to/a/luanti/world \
--   BUILDAT_LUANTI_LUA=builtin/luanti/test/import.lua \
--   bin/buildat_server -m ../apps/vanilla -D ../user
--
-- It says what is there every ten seconds of the world's own clock, which
-- is not ten seconds of yours: an import holds the thread the steps are on,
-- and a step is capped at half a second, so a world that is still
-- generating advances its clock slower than the wall. Leave it running.
--
-- What the importer itself counted -- how many timers and entities it made,
-- and the kinds it could not -- is in the log above this, and is the number
-- to read first.
--
-- **A world whose players are files** rather than a players.sqlite -- one
-- written before 5.x, and one whose world.mt says `player_backend = files`
-- -- is read there too, and says so a player at a time:
--
--   import_world(): players/singleplayer: singleplayer at
--       (-134.7, 11.5, 419.0), hp 16, 4 lists
--   import_world(): 1 players out of files
--   import_world(): 1 of 1 players
--
-- A directory of nothing but a world.mt and a players/ is enough to run
-- that half against, which is the quick way to check it.
--
-- And what the ground under the origin is, which is the fault this check
-- was extended for: an imported world whose sections were generated over is
-- a different world at the same coordinates. The two halves are what the
-- map says and what the mapgen was allowed to touch.
--
-- Against the reference world
-- (/home/celeron55/projects/luanti/worlds/mc2_2026-09-14_2333) the column
-- at (1,*,1) is air down to y=5, mcl_core:sand at 4 and 3, sandstone at 2
-- and 1 and stone from 0 down, and there are cacti within forty of the
-- origin. A column of sand over three sandstone with no cactus anywhere is
-- VoxeLibre's mapgen answering for the same seed, which is what a world
-- that was generated rather than imported looks like.
local generated = {}
core.register_on_generated(function(minp, maxp, seed)
	generated[#generated + 1] = {minp = minp, maxp = maxp}
end)

local function inside(box, p)
	return p.x >= box.minp.x and p.x <= box.maxp.x and
			p.y >= box.minp.y and p.y <= box.maxp.y and
			p.z >= box.minp.z and p.z <= box.maxp.z
end

local function ground()
	local col = {}
	for y = 12, -6, -1 do
		col[#col + 1] = y .. "=" .. core.get_node({x = 1, y = y, z = 1}).name
	end
	core.log("action", "import check: column at (1,*,1): " ..
			table.concat(col, " "))
	local cacti = core.find_nodes_in_area({x = -40, y = -20, z = -40},
			{x = 40, y = 30, z = 40}, {"mcl_core:cactus"})
	core.log("action", "import check: " .. #cacti ..
			" cacti within forty of the origin, " .. #generated ..
			" sections generated by this game")
	-- A world whose map reaches the origin has been generated there by
	-- whoever generated it, and this game's mapgen running over it would
	-- put a fresh world where the read one was. A world that does not
	-- reach the origin is generated there and should be: check a position
	-- its map holds instead of this one.
	for _, box in ipairs(generated) do
		assert(not inside(box, {x = 0, y = 0, z = 0}),
				"the imported world's own origin was generated over")
	end
end

local function say()
	local n, kinds = 0, {}
	for _, le in pairs(core.luaentities or {}) do
		n = n + 1
		local name = le.name or "?"
		kinds[name] = (kinds[name] or 0) + 1
	end
	local parts = {}
	for name, count in pairs(kinds) do
		parts[#parts + 1] = name .. "=" .. count
	end
	table.sort(parts)
	core.log("action", "import check: " .. n .. " entities in the world: " ..
			table.concat(parts, " "))
end

local left = 30
local function again()
	say()
	ground()
	left = left - 1
	if left > 0 then
		core.after(10, again)
	end
end
core.after(10, again)
