#!/bin/bash
# SPDX-License-Identifier: Apache-2.0 OR MIT
# tier: full
# [MAPGEN_STEP]: where a fresh world's on_generated time goes, by mod. A
# VoxeLibre world is generated around a player for a couple of minutes and
# the module's running totals are read out of the server's log -- the worst
# mod of one section was already logged; this is the whole run's.
#
#   MINUTES=2 builtin/luanti/test/mapgen_profile.sh
set -u
here=$(cd "$(dirname "$0")/../../.." && pwd)
me=$(cd "$(dirname "$0")" && pwd)
out="$here/local/mapgen_profile"; mkdir -p "$out"
save=buildat_test_mapgen_profile
MINUTES="${MINUTES:-2}"
cd "$here/Build"
if pgrep -x buildat_server >/dev/null || pgrep -x buildat >/dev/null; then
	echo "a buildat server or client is already running" >&2; exit 2
fi
# A world nobody has generated before, which is the case the item is about
rm -rf "../user/games/vanilla/saves/$save"
cat > "$out/fixture.lua" <<'LUA'
core.settings:set("fixed_map_seed", "5")
LUA
BUILDAT_LUANTI_GAME="${GAME:-mineclone2}" BUILDAT_LUANTI_SAVE="$save" \
	BUILDAT_LUANTI_LUA="$out/fixture.lua" \
	bin/buildat_server -u launcher=1 -m ../games/vanilla -D ../user -P 29790 \
	-l 3 2>&1 | sed -u -e 's/\x1b\[[0-9;]*m//g' > "$out/srv.log" &
for i in $(seq 1 400); do
	grep -q "Mods loaded" "$out/srv.log" 2>/dev/null && break
	sleep 1
done
sleep 5
srv=$(pgrep -x buildat_server | head -1)
[ -n "$srv" ] || { echo "the server did not come up" >&2; exit 1; }
trap 'kill -INT "$srv" 2>/dev/null' EXIT
# A client, because the world is generated around a player and not otherwise
{ echo "delay $((MINUTES * 60000))"; echo "quit"; } > "$out/cmds.txt"
bin/buildat -s localhost:29790 -w 640x480 -l 3 -c @"$out/cmds.txt" 2>&1 |
	sed -u -e 's/\x1b\[[0-9;]*m//g' > "$out/cli.log"
kill -INT "$srv" 2>/dev/null
for i in $(seq 1 60); do kill -0 "$srv" 2>/dev/null || break; sleep 1; done
line=$(grep -a "on_generated by mod after" "$out/srv.log" | tail -1)
if [ -z "$line" ]; then
	echo "FAIL: not one section's worth of mapgen in $MINUTES minutes"
	exit 1
fi
echo "${line#*: }"
# And the sections themselves, for what one costs
grep -a "on_generated at " "$out/srv.log" | sed 's/.*on_generated at/on_generated at/' | tail -3
echo "PASS: the run's mapgen time by mod is above"
