-- The reference shot set's viewpoints, hours and weather, for comparing this
-- module against official Luanti and against extensions/luanti_client.
--
-- **The same file serves all three clients**, because both buildat clients
-- run the game's code through this module and official Luanti runs it as a
-- worldmod. See [OFFICIAL_SHOTS] in doc/plan/rendering_plan.md, which
-- settles the set: mineclone2 only, two worlds, five viewpoints, twenty
-- pictures a client.
--
-- As this module's fixture:
--
--   BUILDAT_LUANTI_GAME=mineclone2 BUILDAT_LUANTI_SAVE=refviews \
--   BUILDAT_LUANTI_IMPORT=~/projects/luanti/worlds/mc2_2026-09-15_0033 \
--   BUILDAT_LUANTI_LUA=../builtin/luanti/test/reference_views.lua \
--   bin/buildat_server -m ../games/luanti_launcher -D ../user
--
-- As official Luanti's, copied to <world>/worldmods/refviews/init.lua.
--
-- **Which viewpoints run is decided by the world's seed**, so the file needs
-- no argument: the second reference world gets 1-4 and the snow fixture gets
-- 5. A world that is neither gets all of them, which is what a hand run
-- wants.
--
-- **Each state is announced in the log** as `REFSHOT <n> <name>`, and the
-- name is the file stem the shot is saved under. A script that drives the
-- shots waits for that line rather than counting seconds, so the two cannot
-- drift apart.
--
-- **The aim is re-asserted every second.** The official client's input is
-- not disabled and the machine is in use, so a stray mouse movement turns
-- the camera; the aim is server-side and authoritative, so it comes back.
-- See [OFFICIAL_SHOTS], "It runs on the user's own desktop".

-- The numbers are the status row's own, out of
-- doc/plan/luanti_module_plan.md. Luanti's look_h is measured the way
-- get_look_horizontal() means it, so it is the row's yaw in radians; its
-- look_v is positive downwards where the row prints positive up, so it is
-- the row's pitch negated. Setting the look first and the position second is
-- what sends both: tell_the_client() goes with set_pos().
local VIEWS = {
	{pos = {x = 319.0, y = 17.5, z = -302.0}, yaw = 273.5, pitch = -6.6},
	{pos = {x = 321.6, y = 17.5, z = -314.3}, yaw = 330.9, pitch = -1.9},
	{pos = {x = 375.1, y = 1.5, z = -351.6}, yaw = 91.1, pitch = -1.4},
	{pos = {x = 432.3, y = 54.5, z = -213.9}, yaw = 223.9, pitch = -5.8},
	-- The snow viewpoint (user, 2026-09-15). In the reference world itself,
	-- not a world of its own: the old snow fixture was generated by
	-- VoxeLibre 0.87 and could not be regenerated under 0.92.3 -- same seed,
	-- same valleys noise, a flower meadow where the reference had snow. One
	-- world for all five viewpoints has no version drift to go wrong.
	{pos = {x = 364.7, y = 112.5, z = 264.9}, yaw = 90.4, pitch = -16.7},
}

-- Which world is which, and which viewpoints belong to it
local SEED_REFERENCE = "2845188330406634615"

-- Luanti's day as one whole unit. The fractions are the plan's own.
local HOURS = {
	["0545"] = 0.2396, ["1000"] = 0.4167, ["1300"] = 0.5417,
	["1500"] = 0.6250, ["1830"] = 0.7708, ["2030"] = 0.8542,
	["0200"] = 0.0833,
}

-- How long each state is held, and how often the aim is put back. Short,
-- because the run shares a desktop -- but not as short as four seconds was
-- (2026-09-16): a client that has just been teleported is still being sent
-- the blocks around it, and four seconds left extensions/luanti_client
-- photographing an empty sky at three of its twenty states. Six puts the
-- shot in the middle of the hold with slack either side, and twenty states
-- is still two minutes a pass.
local HOLD = 6
local REAIM = 1

local function seed_now()
	local s = core.get_mapgen_setting and core.get_mapgen_setting("seed")
	return tostring(s or "")
end

-- The states, in order: every viewpoint this world has, at each of its
-- hours, clear; then every one of them again at 15:00 in rain.
local function states_of(seed)
	-- Viewpoint 5 is the snow one and keeps its own hours: it is a white
	-- field, so what it is for is the top of the range and the night, not
	-- the same three hours the other four carry.
	local by_view
	if seed == SEED_REFERENCE then
		by_view = {
			[1] = {"0545", "1300", "2030"},
			[2] = {"0545", "1300", "2030"},
			[3] = {"0545", "1300", "2030"},
			[4] = {"0545", "1300", "2030"},
			[5] = {"1000", "1830", "0200"},
		}
	else
		by_view = {[1] = {"1300"}, [2] = {"1300"}, [3] = {"1300"},
				[4] = {"1300"}, [5] = {"1300"}}
	end
	local out = {}
	for v = 1, #VIEWS do
		for _, h in ipairs(by_view[v] or {}) do
			out[#out + 1] = {view = v, hour = h, weather = "none"}
		end
	end
	for v = 1, #VIEWS do
		if by_view[v] then
			out[#out + 1] = {view = v, hour = "1500", weather = "rain"}
		end
	end
	return out
end

-- mineclone2 changes the weather on a timer, which would otherwise be a
-- variable nobody recorded. Re-asserted at every state rather than once at
-- load, because the cycle's timer is not the only thing that can change it.
-- Not "thunder": it darkens the sky and is a second variable.
local function hold_weather(kind)
	core.settings:set("mcl_doWeatherCycle", "false")
	-- rawget because this file also runs in games that are not VoxeLibre,
	-- and the vendored builtin's strict.lua warns about reading a global
	-- that nobody declared
	local w = rawget(_G, "mcl_weather")
	if w and w.change_weather then
		w.change_weather(kind, 1000000)
	end
end

-- The three clients are compared at one viewing range and one fog, and it is
-- the official client's: `viewing_range = 200` out of reference_shots.conf,
-- and Luanti's own `fog_start` default of 0.4. For that client this call says
-- what it was already doing and changes nothing; for the two buildat clients
-- it is the only way in, the launcher's own far clip being 400 and its fog
-- starting at 0.7 of it. A ratio between pictures whose fog starts in
-- different places is a ratio about the fog.
--
-- Read, edit, write, rather than a bare set_sky: the sky belongs to the game
-- and only the fog is ours to say. And after the weather rather than before,
-- because changing the weather sets a sky of its own.
local function pin_view(player)
	local sky = player:get_sky(true)
	sky.fog = sky.fog or {}
	sky.fog.fog_distance = 200
	sky.fog.fog_start = 0.4
	player:set_sky(sky)
end

core.register_on_joinplayer(function(player)
	local seed = seed_now()
	local states = states_of(seed)
	core.settings:set("time_speed", "0")
	core.log("action", "REFSHOT world seed " .. seed .. ", " ..
			#states .. " states")

	-- The two call each other, so the name exists before either body does;
	-- a plain `function show()` here would be a global, which the vendored
	-- builtin's strict.lua warns about and which would leak into the game
	local show
	local function aim(i, left)
		if not (player and player:is_player()) then
			return
		end
		local st = states[(i - 1) % #states + 1]
		local v = VIEWS[st.view]
		player:set_look_horizontal(math.rad(v.yaw))
		player:set_look_vertical(math.rad(-v.pitch))
		player:set_pos(v.pos)
		core.set_timeofday(HOURS[st.hour])
		hold_weather(st.weather)
		pin_view(player)
		if left > 0 then
			core.after(REAIM, function() aim(i, left - REAIM) end)
		else
			core.after(REAIM, function() show(i + 1) end)
		end
	end

	function show(i)
		local st = states[(i - 1) % #states + 1]
		local name = seed .. "_vp" .. st.view .. "_" .. st.hour .. "_" ..
				st.weather
		core.log("action", "REFSHOT " .. ((i - 1) % #states + 1) .. " " ..
				name)
		aim(i, HOLD - REAIM)
	end

	core.after(8, function() show(1) end)
end)
