# [VERSION]: writes OUT (a .cpp) with the VERSION file's number and the
# tree's short git hash, "-dirty" appended when the tree has uncommitted
# changes; "unknown" outside a checkout. Run at configure and by a target
# on every build, so the hash is the hash of the tree that was built. The
# file is rewritten only when its text changes, so nothing recompiles for
# nothing. BUILDAT_GIT_HASH in the environment wins: the packaging
# container builds from a git archive, which has no .git.
#   cmake -DSRC=<source dir> -DOUT=<file> -P util/version.cmake
file(READ "${SRC}/VERSION" version)
string(STRIP "${version}" version)
if(DEFINED ENV{BUILDAT_GIT_HASH} AND NOT "$ENV{BUILDAT_GIT_HASH}" STREQUAL "")
	set(hash "$ENV{BUILDAT_GIT_HASH}")
else()
	execute_process(COMMAND git rev-parse --short HEAD
		WORKING_DIRECTORY "${SRC}" OUTPUT_VARIABLE hash
		RESULT_VARIABLE status OUTPUT_STRIP_TRAILING_WHITESPACE
		ERROR_QUIET)
	if(NOT status EQUAL 0)
		set(hash unknown)
	else()
		execute_process(COMMAND git diff --quiet HEAD
			WORKING_DIRECTORY "${SRC}" RESULT_VARIABLE dirty ERROR_QUIET)
		if(NOT dirty EQUAL 0)
			set(hash "${hash}-dirty")
		endif()
	endif()
endif()
set(text "// Generated by util/version.cmake; do not edit
#include \"core/version.h\"
const char *BUILDAT_VERSION = \"${version}\";
const char *BUILDAT_GIT_HASH = \"${hash}\";
")
set(old "")
if(EXISTS "${OUT}")
	file(READ "${OUT}" old)
endif()
if(NOT old STREQUAL text)
	file(WRITE "${OUT}" "${text}")
endif()
