-- Buildat: builtin/voxel_shading/client_lua/module.lua
-- http://www.apache.org/licenses/LICENSE-2.0
-- Copyright 2014 Perttu Ahola <celeron55@gmail.com>
--
-- Draws voxelworld's chunks with PBRVoxel, the shader and technique in this
-- module's client_data. The mesher sets no technique of its own; it hands a
-- shader an atlas, a normal map, a surface map and a skylight value per vertex,
-- and interface/mesh.h says in what. Everything here is what a game could do
-- for itself: a module has no privileges a game lacks, it can just be shared.
--
-- A game needs:
--   zone.zoneTexture = magic.cache:GetResource("TextureCube", M.sky_cubemap)
--   voxel_shading.set_camera(camera_node)
-- and voxelworld.use_skylight set, which is what fills the vertex colors.
local log = buildat.Logger("voxel_shading")
local magic = require("buildat/extension/urho3d")
local voxelworld = require("buildat/module/voxelworld")

local M = {}

-- The sky the shader reflects, and the one it reflects instead where the sky
-- cannot be seen: the same sky dimmed, with no sun disc, going to a flat grey
-- above and below a brighter band at the horizon. Both are generated by
-- games/voxel_lighting/make_client_data.py.
M.sky_cubemap = "voxel_shading/VoxelSky.xml"

local TECHNIQUE = magic.cache:GetResource("Technique",
		"voxel_shading/PBRVoxel.xml")
local INDOOR_SKY = magic.cache:GetResource("TextureCube",
		"voxel_shading/VoxelSkyIndoor.xml")
local TU_ENVIRONMENT = 4 -- sEnvCubeMap in the shader
-- Skylight is four bits per voxel, so the blend steps as the camera crosses a
-- voxel boundary and is eased rather than followed
local INDOOR_BLEND_RATE = 4.0

local camera_node = nil
local indoor_blend = 0.0
local voxel_nodes = {}

local function each_material(node, cb)
	local cg = node:GetComponent("CustomGeometry")
	if not cg then return end
	local i = 0
	while true do
		local m = cg:GetMaterial(i)
		if m == nil then break end
		cb(m)
		i = i + 1
	end
end

voxelworld.sub_geometry_update(function(node)
	voxel_nodes[node:GetID()] = node
end)

voxelworld.sub_material_update(function(node)
	each_material(node, function(m)
		m:SetTechnique(0, TECHNIQUE)
		m:SetTexture(TU_ENVIRONMENT, INDOOR_SKY)
		m:SetShaderParameter("IndoorBlend", indoor_blend)
	end)
end)

-- dt of nil snaps, for when the camera has been moved rather than has moved
function M.update(dt)
	if camera_node == nil then return end
	local v = voxelworld.get_static_voxel(camera_node:GetWorldPosition())
	-- Nothing is generated outside the volume, and nothing shades the camera
	-- there either
	local target = 0.0
	if v:get_id() ~= 0 then
		target = 1.0 - v:get_skylight() / 15.0
	end
	if dt == nil then
		indoor_blend = target
	else
		indoor_blend = indoor_blend + (target - indoor_blend) *
				math.min(1.0, dt * INDOOR_BLEND_RATE)
	end
	-- Follows the camera rather than the geometry, so unlike the technique and
	-- the cube map it cannot be set once per remesh
	for _, node in pairs(voxel_nodes) do
		each_material(node, function(m)
			m:SetShaderParameter("IndoorBlend", indoor_blend)
		end)
	end
end

function M.set_camera(new_camera_node)
	camera_node = new_camera_node
end

return M
-- vim: set noet ts=4 sw=4:
