-- Buildat: builtin/voxel_shading/client_lua/module.lua
-- http://www.apache.org/licenses/LICENSE-2.0
-- Copyright 2014 Perttu Ahola <celeron55@gmail.com>
--
-- Draws voxelworld's chunks with PBRVoxel, the shader and technique in this
-- module's client_data. The mesher sets no technique of its own; it hands a
-- shader an atlas, a normal map, a surface map and a skylight value per vertex,
-- and interface/mesh.h says in what. Everything here is what a game could do
-- for itself: a module has no privileges a game lacks, it can just be shared.
--
-- A game needs:
--   zone.zoneTexture = magic.cache:GetResource("TextureCube", M.sky_cubemap)
--   voxel_shading.create_skybox(scene, sun_dir)
--   voxel_shading.set_camera(camera_node)
--   voxel_shading.update(dt) every frame, or update(nil) to snap
-- and voxelworld.use_skylight set, which is what fills the vertex colors.
local log = buildat.Logger("voxel_shading")
local magic = require("buildat/extension/urho3d")
local voxelworld = require("buildat/module/voxelworld")

local M = {}

-- The sky the shader reflects, generated by
-- games/voxel_lighting/make_client_data.py. Where the sky cannot be seen the
-- shader dims this one by direction rather than reflecting a second, indoor
-- cube map; see the sky visibility note below.
M.sky_cubemap = "voxel_shading/VoxelSky.xml"

local TECHNIQUE = magic.cache:GetResource("Technique",
		"voxel_shading/PBRVoxel.xml")

-- How much of the sky the camera can see, per direction, as a cube of 6x6
-- values per face: 216 numbers, which the shader samples along a pixel's
-- reflection direction and multiplies the sky cube map by. That is the whole
-- indoor/outdoor treatment. There is no second, dimmed cube map to fade to
-- any more, and no single blend value deciding which one a surface gets: this
-- dims the real sky in the directions it cannot be seen and leaves it alone
-- in the directions it can, which is what a baked indoor map was
-- approximating and it cannot get the geometry wrong. Standing in a tunnel
-- mouth, the walls stop reflecting sky while the mouth still does; looking at
-- a cave from outside with no sky in view, nothing reflects a horizon band
-- that is not there.
--
-- 6x6 rather than something coarser because the openings that matter are
-- small: the sky over a tunnel is a few degrees off the tunnel's own
-- direction. A cell here is about 15 degrees across, where a 3x3 cube's is 40
-- and the shader's interpolation spreads one cell over most of a face; the
-- self-check's flat ground reads 0.50 to the sides at this resolution and
-- 0.92 at 3x3, where the ground and the sky above it end up in the same cell.
--
-- The values come from marching rays through the voxel data from the camera.
-- No geometry, depth buffer or render pass is involved. buildat.cast_voxel_rays
-- does the marching, which is what makes this many rays affordable: the same
-- loop written in Lua cost half a millisecond a frame for four rays of twenty
-- voxels, where the engine does 36 of sixty-four in 0.33 ms. It also decides
-- what stops a ray by the voxel registry's own physically_solid, so glass and
-- water are whatever the world says they are.
--
-- A ray answers yes if it gets its whole length without meeting anything and
-- no if something solid stops it. Partial values come from sampling rather
-- than from any softening of that: the rays are jittered within their cells
-- and differently each sweep, and the values are averaged over sweeps, so a
-- cell settles at the fraction of its directions that see sky.
local FACES = 6
local CELLS = 6                 -- Per face, per axis: 6x6
local CELL_COUNT = FACES * CELLS * CELLS
-- Rays per frame. A sweep is one ray per cell, so this is also how often the
-- whole set is renewed: 36 gives a sweep every sixth frame.
local RAYS_PER_UPDATE = 36
-- How far a ray looks. Long, because the length is what makes the answer
-- strict: a ray down digger's tunnel has to reach the end of it to find out
-- that the tunnel is not a way to the sky, and the tunnel is tens of voxels
-- long. Cheap enough that this is not the thing to save on.
local RAY_VOXELS = 64
-- How much of a finished sweep is taken into the values it updates. One ray
-- per cell is a yes or no, so this average over sweeps is what turns the rays
-- into the fraction of a cell that sees sky. At 0.15, with a sweep every sixth
-- frame, a cell settles in under a second and the reflections trail the camera
-- by about that. Following the sweeps any faster puts the rays' own noise on
-- the screen, which reads as the speculars flickering several times a second.
local SKY_VIS_BLEND = 0.15
-- Sweeps averaged when snapping, for a camera that has been moved rather than
-- has moved: the same averaging done at once, so a screenshot taken right
-- after a teleport is as settled as one taken later. This is some thousands of
-- rays in one frame and drops one, which is what a teleport does anyway.
local SNAP_SWEEPS = 8
-- Every chunk material carries the same 216 values, and in a streaming world
-- there are hundreds of them; setting the parameter on all of them at once
-- costs many times what casting the rays does. So they are updated a few at a
-- time against a time budget, which spreads a pass over a fifth of a second
-- or so.
--
-- simplified: materials updated early in a pass hold slightly older values
-- than ones updated late. The values move slowly by design, so this is not
-- visible; if it ever is, the fix is to stop handing every material its own
-- copy -- a render path parameter reaches every shader in the viewport with
-- one call, and a small data texture would be another way.
local PUSH_BUDGET_US = 300
-- Chunks are collected around the camera out to the reach of a ray, and the
-- list is kept until the camera crosses into another chunk: which chunks are
-- within reach does not change until then. Rebuilt every so many sweeps as
-- well, since a streaming world loads chunks under a camera that is standing
-- still.
local VOLUME_MARGIN = RAY_VOXELS
local VOLUME_REFRESH_SWEEPS = 20

-- Which way a cell looks. A direction is placed on the cube by its largest
-- component: that component picks the face, and the other two, divided by it,
-- are the position on the face in -1..1. Going the other way, as here, the
-- face's own axis is +-1 and the other two are the cell's position. The
-- shader takes a direction apart exactly this way, so the two only have to
-- agree with each other and not with anyone's cube map face convention.
--
-- Face f is axis (f - f % 2) / 2 -- 0 x, 1 y, 2 z -- and sign 1 for even f,
-- -1 for odd. u runs along the lowest-numbered axis that is not the face's
-- own and v along the highest.
local FACE_AXES = {
	{major = "x", u = "y", v = "z", sign =  1},
	{major = "x", u = "y", v = "z", sign = -1},
	{major = "y", u = "x", v = "z", sign =  1},
	{major = "y", u = "x", v = "z", sign = -1},
	{major = "z", u = "x", v = "y", sign =  1},
	{major = "z", u = "x", v = "y", sign = -1},
}

local CELL_SIZE = 2.0 / CELLS

-- One table per cell, reused: the sweep rewrites their components rather than
-- building 216 tables of three numbers every time
local DIRS = {}
for i = 1, CELL_COUNT do
	DIRS[i] = {x = 0, y = 0, z = 0}
end

local camera_node = nil
-- What the shader is using now, and what the sweep in progress has found so
-- far, both as one value per cell. Starting fully lit: a game whose voxel
-- data has not arrived yet looks like it is outdoors, which it usually is.
local sky_vis = {}
local sweep_vis = {}
for i = 1, CELL_COUNT do
	sky_vis[i] = 1.0
	sweep_vis[i] = 1.0
end
local sweep_next = 1
local sweep_index = 0
-- Which chunk the collected volumes are for, and how many sweeps ago
local volumes_chunk_x, volumes_chunk_y, volumes_chunk_z = nil, nil, nil
local volumes_age = VOLUME_REFRESH_SWEEPS
local push_queue = {}
local push_queue_n = 0
local push_dirty = false
-- The one table handed to buildat.cast_voxel_rays, reused: only the slice
-- bounds, the origin and the chunk list change between calls
local ray_args = {
	directions = DIRS,
	max_steps = RAY_VOXELS,
	-- Not used: see ray_visibility() on why skylight cannot say which way the
	-- sky is. The engine will stop a ray at a skylight level for callers that
	-- do want that.
	stop_skylight = 0,
	first = 1,
	count = RAYS_PER_UPDATE,
	origin = {x = 0, y = 0, z = 0},
	volumes = {},
}
-- The values as the shader takes them, rebuilt when they change rather than
-- per frame
local sky_vis_buffer = magic.VectorBuffer:new()
local sky_vis_param = nil
local voxel_nodes = {}
local set_sky_vis -- Defined below, used by the material callback above it

local function each_material(node, cb)
	local cg = node:GetComponent("CustomGeometry")
	if not cg then return end
	local i = 0
	while true do
		local m = cg:GetMaterial(i)
		if m == nil then break end
		cb(m)
		i = i + 1
	end
end

voxelworld.sub_geometry_update(function(node)
	voxel_nodes[node:GetID()] = node
end)

voxelworld.sub_material_update(function(node)
	each_material(node, function(m)
		m:SetTechnique(0, TECHNIQUE)
		set_sky_vis(m)
	end)
end)

-- Where in its cell this sweep samples. Two irrational steps, so the point
-- walks the cell instead of landing on a few spots, and the same sequence
-- every run.
local function aim_dirs(index)
	local ju = (index * 0.7548776662) % 1.0 - 0.5
	local jv = (index * 0.5698402909) % 1.0 - 0.5
	local i = 1
	for face = 1, FACES do
		local a = FACE_AXES[face]
		for row = 0, CELLS - 1 do
			for col = 0, CELLS - 1 do
				local d = DIRS[i]
				d[a.major] = a.sign
				d[a.u] = (col + 0.5 + ju) * CELL_SIZE - 1.0
				d[a.v] = (row + 0.5 + jv) * CELL_SIZE - 1.0
				i = i + 1
			end
		end
	end
end

-- A ray answers 1 if nothing stopped it and 0 if something solid did.
--
-- Deliberately a yes or no. What a reflection wants to know is what lies in
-- that direction, and if the answer is rock three voxels away then it is rock,
-- however brightly lit the air in between happens to be. Partial values come
-- from the sampling, not from softening this.
--
-- "Nothing stopped it" means the ray got RAY_VOXELS of the way without
-- meeting anything, which is as much as this asks. Note what is not used
-- here: a voxel's skylight says the sky is open straight up from it, which is
-- nothing to do with whether the sky lies along the ray. Stopping a ray at
-- full skylight looked right and was badly wrong -- at the mouth of digger's
-- tunnel the air is fully lit, so every direction, the tunnel included, came
-- back at 1 and the tunnel got full outdoor reflections.
--
-- Skylight is still what answers for a ray that runs out of loaded chunks
-- part way: the skylight where it stopped is how far along the way out it had
-- got, and believing that is better than calling the edge of the loaded world
-- sky. A ray that never got into voxel data at all is outdoors, which is a
-- camera above the world.
local SKYLIGHT_MAX = 15
local RAY = buildat.VOXEL_RAY

local function ray_visibility(status, skylight, steps)
	if status == RAY.BLOCKED then
		return 0.0
	elseif status == RAY.RANGE then
		return 1.0
	elseif steps <= 1 then
		return 1.0 -- Left the voxel data at once: nothing is around us
	elseif skylight < 0 then
		return 0.0
	end
	return skylight / SKYLIGHT_MAX
end

-- The chunks a ray could reach. The engine picks the one it needs per step out
-- of this list, so it only has to be the right set, not a short one.
--
-- Rebuilding it every sweep cost half a millisecond a frame, which was more
-- than the rays; it is the same set until the camera changes chunk.
local function collect_volumes(origin)
	local cs = voxelworld.chunk_size_voxels
	if cs == nil then
		return false -- voxelworld is not initialized yet
	end
	local cx = math.floor(origin.x / cs.x)
	local cy = math.floor(origin.y / cs.y)
	local cz = math.floor(origin.z / cs.z)
	-- An empty list is not kept: that is a world still loading, and it will
	-- have chunks in a moment
	volumes_age = volumes_age + 1
	if volumes_age < VOLUME_REFRESH_SWEEPS and cx == volumes_chunk_x and
			cy == volumes_chunk_y and cz == volumes_chunk_z and
			ray_args.volumes[1] ~= nil then
		return true
	end
	volumes_chunk_x, volumes_chunk_y, volumes_chunk_z = cx, cy, cz
	volumes_age = 0
	local volumes = ray_args.volumes
	for i = #volumes, 1, -1 do
		volumes[i] = nil
	end
	local n = 0
	for z = math.floor((origin.z - VOLUME_MARGIN) / cs.z),
			math.floor((origin.z + VOLUME_MARGIN) / cs.z) do
		for y = math.floor((origin.y - VOLUME_MARGIN) / cs.y),
				math.floor((origin.y + VOLUME_MARGIN) / cs.y) do
			for x = math.floor((origin.x - VOLUME_MARGIN) / cs.x),
					math.floor((origin.x + VOLUME_MARGIN) / cs.x) do
				local node = voxelworld.get_static_node(
						buildat.Vector3(x, y, z))
				local volume = node and voxelworld.get_volume(node) or nil
				if volume ~= nil then
					n = n + 1
					volumes[n] = {x = x, y = y, z = z, volume = volume}
				end
			end
		end
	end
	ray_args.chunk_size = cs
	ray_args.registry = voxelworld.get_voxel_registry()
	return n > 0
end

-- One slice of a sweep: cast the rays for cells first..first+count-1 and keep
-- what they found
local function cast_slice(first, count)
	ray_args.first = first
	ray_args.count = count
	local out = buildat.cast_voxel_rays(ray_args)
	local status, skylight, steps = out.status, out.skylight, out.steps
	for i = 1, out.count do
		sweep_vis[first + i - 1] =
				ray_visibility(status[i], skylight[i], steps[i])
	end
end

-- No chunks anywhere near: a camera above the world, or one whose world has
-- not arrived. Outdoors is the right answer for both.
local function sweep_all_open()
	for i = 1, CELL_COUNT do
		sweep_vis[i] = 1.0
	end
end

local function begin_sweep()
	sweep_next = 1
	sweep_index = sweep_index + 1
	aim_dirs(sweep_index)
end

-- f is how much of the sweep to take; 1.0 replaces the values outright
local function finish_sweep(f)
	for i = 1, CELL_COUNT do
		sky_vis[i] = sky_vis[i] + (sweep_vis[i] - sky_vis[i]) * f
	end
	-- One parameter of 216 floats rather than 216 parameters: Urho sets a
	-- Variant buffer as a float array, sized by what the uniform declares
	sky_vis_buffer:Clear()
	for i = 1, CELL_COUNT do
		sky_vis_buffer:WriteFloat(sky_vis[i])
	end
	sky_vis_param = magic.Variant(sky_vis_buffer)
end


set_sky_vis = function(m)
	if sky_vis_param ~= nil then
		m:SetShaderParameter("SkyVis", sky_vis_param)
	end
end

-- A finished sweep does not push anything itself; it marks the values as
-- moved on and service_push() works through the nodes from there
local function push_sky_vis()
	push_dirty = true
end

local function service_push()
	if push_queue_n == 0 then
		if not push_dirty then return end
		push_dirty = false
		for id, _ in pairs(voxel_nodes) do
			push_queue_n = push_queue_n + 1
			push_queue[push_queue_n] = id
		end
	end
	local t0 = buildat.get_time_us()
	while push_queue_n > 0 do
		local node = voxel_nodes[push_queue[push_queue_n]]
		push_queue[push_queue_n] = nil
		push_queue_n = push_queue_n - 1
		if node ~= nil then
			each_material(node, set_sky_vis)
		end
		if buildat.get_time_us() - t0 >= PUSH_BUDGET_US then
			break
		end
	end
end

-- dt of nil snaps, for when the camera has been moved rather than has moved
function M.update(dt)
	if camera_node == nil then return end
	local origin = camera_node:GetWorldPosition()
	ray_args.origin.x = origin.x
	ray_args.origin.y = origin.y
	ray_args.origin.z = origin.z
	if dt == nil then
		-- Several sweeps at once, averaged the way the easing would have
		-- averaged them over a second. A single sweep is one ray per cell,
		-- which is too coarse to look at.
		for sweep = 1, SNAP_SWEEPS do
			begin_sweep()
			if collect_volumes(origin) then
				cast_slice(1, CELL_COUNT)
			else
				sweep_all_open()
			end
			finish_sweep(sweep == 1 and 1.0 or 1.0 / sweep)
		end
		begin_sweep()
		-- A snap is for a camera that has been put somewhere, so the whole
		-- scene takes the new values at once rather than over a pass
		for _, node in pairs(voxel_nodes) do
			each_material(node, set_sky_vis)
		end
		push_dirty = false
		for i = push_queue_n, 1, -1 do
			push_queue[i] = nil
		end
		push_queue_n = 0
		return
	end
	if sweep_next == 1 and not collect_volumes(origin) then
		sweep_all_open()
		finish_sweep(SKY_VIS_BLEND)
		begin_sweep()
		push_sky_vis()
		return
	end
	service_push()
	local count = math.min(RAYS_PER_UPDATE, CELL_COUNT - sweep_next + 1)
	cast_slice(sweep_next, count)
	sweep_next = sweep_next + count
	if sweep_next > CELL_COUNT then
		finish_sweep(SKY_VIS_BLEND)
		begin_sweep()
		push_sky_vis()
	end
end

-- The sky the world stands under, drawn by VoxelSkybox.glsl in the same
-- gradient the cube map is baked in. sun_dir points the way the light travels,
-- as a Light's direction does, so the sun itself is the other way.
function M.create_skybox(scene, sun_dir)
	local node = scene:CreateChild("Sky")
	local skybox = node:CreateComponent("Skybox")
	skybox:SetModel(magic.cache:GetResource("Model", "Models/Box.mdl"))
	local material = magic.Material:new()
	material:SetTechnique(0, magic.cache:GetResource("Technique",
			"voxel_shading/VoxelSkybox.xml"))
	material:SetShaderParameter("SunDirection", magic.Vector3(
			-sun_dir.x, -sun_dir.y, -sun_dir.z))
	skybox.material = material
	return node
end

function M.set_camera(new_camera_node)
	camera_node = new_camera_node
end

return M
-- vim: set noet ts=4 sw=4:
