-- The reference shot set: what is photographed, from where, when. Data and
-- no behaviour; runner.lua is the behaviour and holds no numbers. build.sh
-- concatenates the two into the fixture each client runs and reads this
-- file alone, with plain lua, for what the shell runners need. See
-- [REFVIEWS_MOD] and [OFFICIAL_SHOTS] in doc/plan/rendering_plan.md.
--
-- The world's seed is not here: it lives in map_meta.txt, in Luanti's own
-- format, and build.sh hands it to the fixture as REFSHOT_SEED.
rawset(_G, "REFSET", {
	-- The frame, for every client: a ratio between pictures of different
	-- sizes is a ratio about the size
	frame = {w = 1280, h = 720},

	-- The viewing range, the same for the three clients and no fog. Default
	-- 150 (user, 2026-09-17: 44% less world than 200 for the same picture).
	-- Every set directory carries it as _r<RANGE>.
	range = 150,

	-- How far the sun's orbit is tilted, in degrees, for the pbr set and
	-- its render: the client's own default (luanti_sky.OWN_ORBIT_TILT),
	-- since pbr is measured against the render and an axis-aligned sun
	-- lights one face of a block and leaves a corner probe degenerate.
	-- The parity modes take zero, since official Luanti does not tilt.
	-- See [PBR_FIT] 2c.
	orbit_tilt = 22.8,

	-- How long each timed state is held, in seconds. **Calibrated rather
	-- than picked** (2026-09-16) -- the ladder is in the rendering history
	-- under [PROBE_CYCLE]: what broke below six was the run's total length,
	-- not the hold. Only the timed pass uses it; the module's clients
	-- answer per state instead.
	hold = 6,

	-- The numbers are the status row's own, out of
	-- doc/plan/luanti_module_plan.md. Luanti's look_h is measured the way
	-- get_look_horizontal() means it, so it is the row's yaw in radians; its
	-- look_v is positive downwards where the row prints positive up, so it
	-- is the row's pitch negated.
	views = {
		{pos = {x = 319.0, y = 17.5, z = -302.0}, yaw = 273.5, pitch = -6.6},
		{pos = {x = 321.6, y = 17.5, z = -314.3}, yaw = 330.9, pitch = -1.9},
		{pos = {x = 375.1, y = 1.5, z = -351.6}, yaw = 91.1, pitch = -1.4},
		{pos = {x = 432.3, y = 54.5, z = -213.9}, yaw = 223.9, pitch = -5.8},
		-- The snow viewpoint (user, 2026-09-15). In the reference world
		-- itself, not a world of its own: the old snow fixture was
		-- generated by VoxeLibre 0.87 and could not be regenerated under
		-- 0.92.3 -- same seed, same valleys noise, a flower meadow where
		-- the reference had snow.
		{pos = {x = 364.7, y = 112.5, z = 264.9}, yaw = 90.4, pitch = -16.7},
		-- Cave trio (2026-09-17), 13:00 only. Physics frozen; eyes in air.
		-- 6 HDR in: cave_pick11/cave_vp7.png
		-- 7 HDR out: cave_pick17/cave_fwd2.png
		-- 8 into the dark: cave_pick3/cave_d_dark_y15.png, 1.5 voxels
		-- forward along the look (yaw 56.3, pitch -20).
		{pos = {x = 326.2, y = 9.2, z = -294.8}, yaw = 56.3, pitch = -16.0},
		{pos = {x = 310.5, y = 0.2, z = -286.2}, yaw = 241.3, pitch = 26.0},
		{pos = {x = 324.3, y = 1.0, z = -288.7}, yaw = 56.3, pitch = -20.0},
	},

	-- One lamp in the reference ([LAMP_REF]): a light source placed by
	-- the fixture at the far end of the vp8 cave, so that the client's
	-- lamp term has a number to be fitted to -- the render emits from
	-- the node's tile at LAMP_RADIANCE in pathtrace_render.py. A world
	-- position, set as it is: a march along the look put it on the ledge
	-- twelve nodes out at 313,0,-286, and the user moved it seven further
	-- along -x and three up (2026-09-18) -- the far end, top-left of the
	-- frame, so the bottom of the view stays dark.
	lamps = {
		{view = 8, node = "mcl_nether:glowstone",
			pos = {x = 306, y = 3, z = -286}},
	},

	-- One bore in the reference ([STAIR_VIEW], user 2026-09-20): the
	-- one-wide staircase that broke twice in a day, dug by the fixture
	-- along vp1's own line of sight so the camera looks straight down
	-- it. The trace: from vp1's eye (its feet plus Luanti's 1.625)
	-- toward +X pitched -30 degrees; every voxel whose centre is within
	-- `half` of the line in Y goes to air (0.8: at thirty degrees 0.5
	-- left the steps touching at their corners only, user 2026-09-20),
	-- ten columns deep counted from the first that held anything solid.
	-- The trace is the number; which voxels it meets is the world's,
	-- the same in every run.
	bore = {view = 1, from = {x = 319.0, y = 17.5 + 1.625, z = -302.0},
		pitch = -30, half = 0.8, depth = 10},

	-- Luanti's day as one whole unit. The fractions are the plan's own.
	hours = {
		["0545"] = 0.2396, ["1000"] = 0.4167, ["1300"] = 0.5417,
		["1500"] = 0.6250, ["1830"] = 0.7708, ["2030"] = 0.8542,
		["0200"] = 0.0833,
	},

	-- Which hours each viewpoint is shot at, clear. Viewpoint 5 is the snow
	-- one and keeps its own: it is a white field, so what it is for is the
	-- top of the range and the night. The caves are 13:00 only.
	hours_of_view = {
		[1] = {"0545", "1300", "2030"},
		[2] = {"0545", "1300", "2030"},
		[3] = {"0545", "1300", "2030"},
		[4] = {"0545", "1300", "2030"},
		[5] = {"1000", "1830", "0200"},
		[6] = {"1300"},
		[7] = {"1300"},
		[8] = {"1300"},
	},
	-- Rain is the surface set, at 15:00; a cave at 15:00 in rain is not a
	-- third lighting question
	rain_views = {1, 2, 3, 4, 5},
	rain_hour = "1500",
	-- What a world that is not the reference gets: everything at 13:00,
	-- which is what a hand run wants
	hand_hour = "1300",

	-- The states a probe cycle shoots: the pictures probes.sh reads and
	-- nothing else. See [PROBE_CYCLE].
	probe_states = {
		{view = 4, hour = "1300", weather = "none"},
		{view = 5, hour = "1000", weather = "none"},
		{view = 7, hour = "1300", weather = "none"},
		-- and the fit's and the sky's ([PBR_FIT])
		{view = 1, hour = "1300", weather = "none"},
		{view = 1, hour = "0545", weather = "none"},
		{view = 5, hour = "0200", weather = "none"},
		{view = 3, hour = "0545", weather = "none"},
		{view = 2, hour = "0545", weather = "none"},
		-- and the translucency's: canopy_dawn is vp4 05:45 ([PBR_FIT] 3b;
		-- it read a stale picture for a day without this)
		{view = 4, hour = "0545", weather = "none"},
		-- and the lamp's ([LAMP_REF])
		{view = 8, hour = "1300", weather = "none"},
	},
	-- One dump per viewpoint at its primary hour, for [PATH_TRACE_REF].
	-- Caves first: a later state that never draws must not drop them.
	pathtrace_states = {
		{view = 6, hour = "1300", weather = "none"},
		{view = 7, hour = "1300", weather = "none"},
		{view = 8, hour = "1300", weather = "none"},
		{view = 1, hour = "1300", weather = "none"},
		{view = 2, hour = "1300", weather = "none"},
		{view = 3, hour = "1300", weather = "none"},
		{view = 4, hour = "1300", weather = "none"},
		{view = 5, hour = "1000", weather = "none"},
	},

	-- The crops probes.sh reads, facts about the viewpoints: a name, the
	-- picture as vp<view>_<hour>, an ImageMagick crop, and what it is for.
	-- See [RENDER_MODES] and [GREEN_BIAS].
	probes = {
		{"grass", "vp4_1300", "40x30+280+545", "colourised, top face: the one GREEN_BIAS owns"},
		{"grasstop", "vp4_1300", "200x30+500+560", "the same, over the whole field"},
		{"grassside", "vp4_1300", "60x40+1100+500", "the same node's SIDE: says whether the fault is the face or the palette"},
		{"stone", "vp4_1300", "30x20+625+320", "CONTROL, no palette: must not move"},
		{"dirt", "vp4_1300", "30x20+45+420", "colourised, weaker"},
		{"cave", "vp4_1300", "60x40+610+360", "the floor, TOO_BRIGHT's black caves"},
		{"cavedark", "vp6_1300", "80x80+600+320", "HDR in, looking into the dark"},
		{"caveout", "vp7_1300", "80x80+600+280", "HDR out, the bright opening"},
		{"cavedeep", "vp8_1300", "80x80+600+320", "into the dark from inside"},
		{"wall", "vp4_1300", "30x40+880+300", "shaded: what tells the modes apart"},
		{"snow", "vp5_1000", "60x40+420+540", "no colour of its own to hide a cast"},
		{"leaf", "vp5_1000", "50x30+700+560", "colourised, against snow"},
	},
})
