// http://www.apache.org/licenses/LICENSE-2.0
// Copyright 2014 Perttu Ahola <celeron55@gmail.com>
#pragma once
#include "interface/event.h"
#include "interface/server.h"
#include "interface/module.h"
#include "interface/voxel.h"
#include "interface/voxel_volume.h"
#include <PolyVoxCore/Vector.h>
#include <PolyVoxCore/Region.h>
#include <PolyVoxCore/RawVolume.h>
#include <functional>

namespace Urho3D
{
	class Context;
	class Scene;
	class Node;
}

namespace main_context
{
	struct OpaqueSceneReference;
	typedef OpaqueSceneReference* SceneReference;
}

namespace voxelworld
{
	namespace magic = Urho3D;
	namespace pv = PolyVox;

	using interface::VoxelVolume;
	using interface::VoxelInstance;
	using main_context::SceneReference;

	struct GenerationRequest: public interface::Event::Private
	{
		SceneReference scene;
		pv::Vector3DInt16 section_p;

		GenerationRequest(SceneReference scene,
				const pv::Vector3DInt16 &section_p):
			scene(scene),
			section_p(section_p)
		{}
	};

	struct NodeVolumeUpdated: public interface::Event::Private
	{
		SceneReference scene;
		uint node_id;
		bool is_static_chunk = false;
		pv::Vector3DInt32 chunk_p; // Only set if is_static_chunk == true

		NodeVolumeUpdated(SceneReference scene, uint node_id,
				bool is_static_chunk, const pv::Vector3DInt32 &chunk_p):
			scene(scene), node_id(node_id),
			is_static_chunk(is_static_chunk), chunk_p(chunk_p)
		{}
	};

	struct Instance;

	struct CommitHook
	{
		virtual ~CommitHook(){}
		virtual void in_thread(voxelworld::Instance *world,
				const pv::Vector3DInt32 &chunk_p,
				VoxelVolume &volume){}
		virtual void in_scene(voxelworld::Instance *world,
				const pv::Vector3DInt32 &chunk_p, magic::Node *n){}
	};

	struct Instance
	{
		virtual interface::VoxelRegistry* get_voxel_reg() = 0;

		virtual void add_commit_hook(up_<CommitHook> hook) = 0;

		virtual pv::Vector3DInt16 get_section_size_voxels() = 0;

		virtual pv::Region get_section_region_voxels(
				const pv::Vector3DInt16 &section_p) = 0;

		virtual const pv::Vector3DInt16& get_chunk_size_voxels() = 0;

		virtual pv::Region get_chunk_region_voxels(
				const pv::Vector3DInt32 &chunk_p) = 0;

		virtual void load_or_generate_section(
				const pv::Vector3DInt16 &section_p) = 0;

		virtual void unload_section(const pv::Vector3DInt16 &section_p) = 0;

		virtual bool is_section_loaded(const pv::Vector3DInt16 &section_p) = 0;

		virtual void set_voxel(const pv::Vector3DInt32 &p,
				const VoxelInstance &v,
				bool disable_warnings = false) = 0;

		// Write a generated volume into the world, by priority per voxel: a
		// voxel that has not been generated yet (VOXELTYPEID_UNDEFINED) takes
		// anything, an empty one takes anything that is not empty, and one
		// that already holds something is left alone -- it is either terrain
		// that was generated by whoever owns that section or something that
		// was built there since, and neither should be overwritten by a
		// neighbour's padding. A voxel that is undefined in the volume is
		// skipped, so a generator can leave holes for others to fill.
		//
		// The volume may reach outside the section it was generated for.
		// With create_missing_sections, a section it reaches into that does
		// not exist yet is created and left ungenerated, holding only what
		// the volume puts in it; it is generated for real when someone asks
		// for it. Without it, such a part of the volume is dropped.
		//
		// "Empty" is VoxelDefinition::fully_empty: a voxel that nothing
		// occupies. A voxel that merely leaves the faces against it undrawn
		// (EDGEMATERIALID_EMPTY) may still hold a mesh of its own, and counts
		// as something standing there.
		virtual void merge_volume(
				const VoxelVolume &volume,
				bool create_missing_sections) = 0;

		// Maintain VoxelInstance::get_skylight() of every voxel in the world.
		// Off by default; a world that does not want skylight pays nothing and
		// keeps whatever is in those bits. Once on, the light is kept up to
		// date by set_voxel(), including through generation, and is settled
		// before commit() meshes anything.
		//
		// Light enters from above the top of the world region at full
		// strength, falls through anything that transmits light without
		// losing any, and spreads sideways and upwards losing one step per
		// voxel. A voxel transmits light if its edge material is
		// EDGEMATERIALID_EMPTY, which is the same test the mesher uses to
		// decide whether a face is drawn against it.
		//
		// simplified: transparency is that one test, so glass would have to
		// be a light barrier or a hole in the terrain. A voxel definition
		// flag of its own is the upgrade path.
		virtual void set_skylight_enabled(bool enabled) = 0;

		virtual size_t num_buffers_loaded() = 0;

		virtual void commit() = 0;

		virtual VoxelInstance get_voxel(const pv::Vector3DInt32 &p,
				bool disable_warnings = false) = 0;

		// NOTE: There is no interface in here for directly accessing chunk
		// volumes of static nodes, because it is so much more hassly and was
		// tested to improve speed only by 53% compared to the current very
		// robust interface.
	};

	struct Interface
	{
		// physics_enabled gives the chunk nodes server-side Bullet collision
		// shapes. Off by default: they cost more than the world generation
		// they are built alongside, and only a game that has the server
		// simulate something against the terrain queries them at all. A game
		// that reads terrain hits out of the voxel volumes does not need them.
		// It is a parameter and not a setting because the initial sections are
		// created here. The client has its own switch; see physics_distance in
		// voxelworld's client_lua.
		virtual void create_instance(SceneReference scene_ref,
				const pv::Region &region, bool physics_enabled = false) = 0;
		virtual void delete_instance(SceneReference scene_ref) = 0;

		virtual Instance* get_instance(SceneReference scene_ref) = 0;

		virtual void commit() = 0;
	};

	inline bool access(interface::Server *server,
			std::function<void(voxelworld::Interface*)> cb)
	{
		return server->access_module("voxelworld", [&](interface::Module *module){
			auto *iface = (voxelworld::Interface*)module->check_interface();
			cb(iface);
			iface->commit();
		});
	}

	inline bool access(interface::Server *server, SceneReference scene_ref,
			std::function<void(voxelworld::Instance*instance)> cb)
	{
		return access(server, [&](voxelworld::Interface *i){
			voxelworld::Instance *instance =
					check(i->get_instance(scene_ref));
			cb(instance);
		});
	}
}

// vim: set noet ts=4 sw=4:
